version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    stdin_open: true
    tty: true
    networks:
      test_network:
        ipv4_address: 172.28.0.2

#  cloudera:
#    image: cloudera/quickstart
#    container_name: cloudera
#    privileged: true
#    command: /usr/bin/docker-quickstart
#    ports:
#      - "8020:8020"   # HDFS
#      - "8022:22"     # SSH
#      - "7180:7180"   # Cloudera Manager
#      - "8888:8888"   # Hue
#      - "11000:11000" # Oozie
#      - "50070:50070" # HDFS Rest Namenode
#      - "50075:50075" # HDFS Rest Datanode
#      - "2181:2181"   # Zookeeper
#      - "8088:8088"   # YARN Resource Manager
#      - "19888:19888" # MapReduce Job History
#      - "50030:50030" # MapReduce Job Tracker
#      - "8983:8983"   # Solr
#      - "16000:16000" # Sqoop Metastore
#      - "8042:8042"   # YARN Node Manager
#      - "60010:60010" # HBase Master
#      - "60030:60030" # HBase Region
#      - "9090:9090"   # HBase Thrift
#      - "8080:8080"   # HBase Rest
#      - "7077:7077"   # Spark Master
#    stdin_open: true
#    tty: true
#    volumes:
#      - /var/shared_cloudera_quickstart:/media/shared_from_local
#    networks:
#      test_network:
#        ipv4_address: 172.28.0.3

  jupyter:
    build:
      context: ./dockerfiles
      dockerfile: dockerfile-jupyter
    container_name: jupyter
    ports:
      - "8888:8888"
    command: start.sh jupyter notebook --NotebookApp.token=''
    volumes:
      - ./code:/home/jovyan/code
    stdin_open: true
    tty: true 
    networks:
      test_network:
        ipv4_address: 172.28.0.4

networks:
  test_network:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 172.28.0.0/16
